# Generated by Django 5.0.4 on 2024-10-27 10:59

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('city_or_town', models.CharField(choices=[('Agno', 'Agno'), ('Aguilar', 'Aguilar'), ('Alcala', 'Alcala'), ('Anda', 'Anda'), ('Asingan', 'Asingan'), ('Balungao', 'Balungao'), ('Bani', 'Bani'), ('Basista', 'Basista'), ('Bautista', 'Bautista'), ('Bayambang', 'Bayambang'), ('Binalonan', 'Binalonan'), ('Binmaley', 'Binmaley'), ('Bolinao', 'Bolinao'), ('Bugallon', 'Bugallon'), ('Burgos', 'Burgos'), ('Calasiao', 'Calasiao'), ('Dasol', 'Dasol'), ('Infanta', 'Infanta'), ('Labrador', 'Labrador'), ('Laoac', 'Laoac'), ('Lingayen', 'Lingayen'), ('Mabini', 'Mabini'), ('Malasiqui', 'Malasiqui'), ('Manaoag', 'Manaoag'), ('Mangaldan', 'Mangaldan'), ('Mangatarem', 'Mangatarem'), ('Mapandan', 'Mapandan'), ('Natividad', 'Natividad'), ('Pozorrubio', 'Pozorrubio'), ('Rosales', 'Rosales'), ('San Fabian', 'San Fabian'), ('San Jacinto', 'San Jacinto'), ('San Manuel', 'San Manuel'), ('San Nicolas', 'San Nicolas'), ('San Quintin', 'San Quintin'), ('Santa Barbara', 'Santa Barbara'), ('Santa Maria', 'Santa Maria'), ('Santo Tomas', 'Santo Tomas'), ('Sison', 'Sison'), ('Sual', 'Sual'), ('Tayug', 'Tayug'), ('Umingan', 'Umingan'), ('Urbiztondo', 'Urbiztondo'), ('Villasis', 'Villasis'), ('Alaminos', 'Alaminos'), ('Dagupan', 'Dagupan'), ('San Carlos', 'San Carlos'), ('Urdaneta', 'Urdaneta')], max_length=100)),
                ('category', models.CharField(blank=True, choices=home.models.get_categories, max_length=100, null=True)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TouristSpotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourist_spot_images/')),
                ('tourist_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.touristspot')),
            ],
        ),
    ]
