# Generated by Django 5.0.4 on 2024-11-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_accomodation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
