# Generated by Django 5.0.4 on 2024-11-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_tourist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
