# Generated by Django 5.0.4 on 2024-11-19 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tourist_gender_alter_tourist_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='avatar',
            field=models.ImageField(blank=True, default='/kirby.png', null=True, upload_to='tourist_avatars/'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_visited', models.CharField(max_length=100)),
                ('visited_with', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review_title', models.CharField(max_length=100)),
                ('review_content', models.TextField()),
                ('tourist_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.touristspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial_images/')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.testimonial')),
            ],
        ),
    ]
