# Generated by Django 5.0.4 on 2024-11-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_testimonial_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='gender',
        ),
    ]
