# Generated by Django 5.0.4 on 2024-11-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_tourist_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='length_of_stay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
